#!/usr/bin/env node
// Validates .planning/VENTURE/*.md and, if all pass, flips venture.committed=true
// and writes ADR 0001.

import { existsSync, readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const ROOT = resolve(dirname(__filename), "..");

const BOOTSTRAP = join(ROOT, ".planning", ".bootstrap.json");
const VENTURE  = join(ROOT, ".planning", "VENTURE");
const ADR_DIR  = join(ROOT, ".planning", "adr");
const STATE    = join(ROOT, ".planning", "STATE.md");

const REQUIRED = [
  "SKILLSET.md", "OPPORTUNITIES.md", "RESEARCH.md",
  "CATEGORIZATION.md", "MARKET-TEST.md", "COMMITMENT.md"
];

function die(msg) { console.error(`xx  ${msg}`); process.exit(1); }
function ok(msg)  { console.log(`ok  ${msg}`); }

if (!existsSync(BOOTSTRAP)) die(".planning/.bootstrap.json missing. Run 'npm run bootstrap' first.");
const boot = JSON.parse(readFileSync(BOOTSTRAP, "utf8"));
if (!boot.bootstrapped) die("Bootstrap not complete. Run 'npm run bootstrap' first.");
if (boot.venture?.committed) die("Venture is already committed. To re-open the gate, write a new ADR, then manually reset venture.committed.");

let failed = false;
for (const file of REQUIRED) {
  const path = join(VENTURE, file);
  if (!existsSync(path)) { console.error(`xx  missing: ${file}`); failed = true; continue; }
  const content = readFileSync(path, "utf8");

  if (/STATUS:\s*TODO/i.test(content)) {
    console.error(`xx  ${file}: still marked STATUS: TODO`);
    failed = true;
  }
  const placeholderMatches = content.match(/<!--\s*fill(\s*:[^-]*)?\s*-->/gi);
  if (placeholderMatches && placeholderMatches.length > 0) {
    console.error(`xx  ${file}: ${placeholderMatches.length} unfilled placeholder(s) remain`);
    failed = true;
  }
}

if (failed) die("Commit refused. Fix the above and re-run.");
ok("All VENTURE files validated.");

const commitmentContent = readFileSync(join(VENTURE, "COMMITMENT.md"), "utf8");

const chosenLine = commitmentContent.match(/One-line description:\s*([^\n]+)/i);
const chosen = chosenLine ? chosenLine[1].trim() : "unspecified";
if (chosen === "" || chosen.startsWith("<!--")) die("COMMITMENT.md: 'One-line description' is empty.");

const signatureLine = commitmentContent.match(/Signed by typing full name:\s*([^\n]+)/i);
const signed = signatureLine ? signatureLine[1].trim() : "";
if (!signed || signed.startsWith("<!--")) die("COMMITMENT.md: signature line is empty.");

const capitalLine = commitmentContent.match(/Maximum cash out-of-pocket through day 90[^:]*:\s*([^\n]+)/i);
const capital = capitalLine ? capitalLine[1].trim() : "";
if (!capital || /\d/.test(capital) === false || capital.startsWith("<!--")) die("COMMITMENT.md: capital-at-risk must be a number.");

const now = new Date().toISOString();
const today = now.slice(0, 10);

if (!existsSync(ADR_DIR)) mkdirSync(ADR_DIR, { recursive: true });
const adrPath = join(ADR_DIR, "0001-venture-commitment.md");
const adr = `# ADR 0001 - Venture Commitment

- Status: accepted
- Date: ${today}
- Deciders: ${signed}

## Context

This ADR is auto-generated by \`npm run commit\`. It freezes the snapshot that
unlocked code scaffolding for the project.

## Decision

Commit to the opportunity described in \`.planning/VENTURE/COMMITMENT.md\`:

> ${chosen}

## Snapshot (frozen at commit time)

\`\`\`
${commitmentContent.trim()}
\`\`\`

## Consequences

### Positive
- Discovery gate closed; build phase unlocked.

### Negative / Accepted trade-offs
- Alternative candidates in CATEGORIZATION.md are dropped until day 90.
- Re-opening the gate before day 90 requires a new ADR.

## Reversal Cost

Medium. Reversal is legitimate if kill criteria in COMMITMENT.md are met, or if
a new ADR supersedes this one.
`;
writeFileSync(adrPath, adr, "utf8");
ok(`ADR written: .planning/adr/0001-venture-commitment.md`);

boot.venture = {
  ...boot.venture,
  committed: true,
  committedAt: now,
  chosenOpportunity: chosen,
  commitmentAdr: "0001-venture-commitment.md"
};
boot.currentPhase = 1;
writeFileSync(BOOTSTRAP, JSON.stringify(boot, null, 2) + "\n", "utf8");
ok("venture.committed = true");

if (existsSync(STATE)) {
  let state = readFileSync(STATE, "utf8");
  state = state.replace(/Phase:\s*\d+ of \d+/, "Phase: 1 of 4");
  state = state.replace(/Plan:.*\n/, `Plan: Phase 1 Foundation (auto-set by commit on ${today})\n`);
  state = state.replace(/Status:.*\n/, `Status: Venture committed; build phase active.\n`);
  state = state.replace(/Progress:\s*\[.*\]\s*\d+%/, "Progress: [##--------] 10%");
  writeFileSync(STATE, state, "utf8");
  ok(".planning/STATE.md updated to Phase 1.");
}

console.log(`
---------------------------------------------------------------
GATE OPEN - code scaffolding unlocked.
---------------------------------------------------------------
Next recommended
----------------
Surface : Cursor Plan mode
Mode    : plan
Model   : Cursor Auto (or Claude Sonnet 4.6 via Cursor model picker)
Action  : open .planning/ROADMAP.md, then in Claude Code run '/plan-phase'.
Why     : Phase 1 Foundation needs a task breakdown before execution.
---------------------------------------------------------------
`);
